base/urls.py
from django.urls import path, re_path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [

    # ---------------------- create -------------------#
    path('', views.Dashboard, name='Dashboard'),
    re_path(r'login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', views.logout, name='logout'),
    # ---------------------- liste -------------------#
    # ---------------------- detail -------------------#

    # ---------------------- autre -------------------#

]

gestion_commercial/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = ([
    path('admin/', admin.site.urls),
    re_path(r'^', include(('base.urls', 'base'), namespace="base")),
    re_path(r'^', include(('stock.urls', 'stock'), namespace="stock")),
    re_path(r'^', include(('client.urls', 'client'), namespace="client")),
    re_path(r'^', include(('dashboard.urls', 'dashboard'), namespace="dashboard")),
    re_path(r'^', include(('produit.urls', 'produit'), namespace="produit")),
    re_path(r'^', include(('venteAchats.urls', 'venteAchats'), namespace="venteAchats")),
    re_path(r'^', include(('commande.urls', 'commande'), namespace="commandes")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
if settings.DEBUG:  # Assurez-vous que les URL de debug toolbar ne sont chargées qu'en mode développement
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

base/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.exceptions import ValidationError


from django.utils.functional import lazy


class AbstractBaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted = models.BooleanField(default=False)


    class Meta:
        abstract = True
        default_permissions = ['add', 'change', 'view', "soft_delete"]

    def soft_delete(self):
        # Get the classes that reference self that are instances of BaseModel and are not soft deleted
        for f in self._meta.get_fields():
            if f.one_to_many or f.one_to_one:
                if issubclass(f.related_model, AbstractBaseModel) and \
                        f.related_model.objects.filter(**{f.field.name: self}, deleted=False).exists():
                    raise ValidationError(
                        "Vous ne pouvez pas supprimer cet élément car il est référencé par au moins un élément de type {0}".format(
                            f.related_model._meta.verbose_name))
        self.deleted = True
        self.save()




class Societe(models.Model):
    FORMES = (
        ('sarl', 'SARL'),
        ('sarlau', 'SARL AU'),
        ('sa', 'SA'),
    )

    class Meta:
        ordering = ["nom"]
        verbose_name_plural = "Sociétés"
        default_permissions = ['add', 'change', 'view']
        db_table = "base_company"

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    verbose_name = "Société"
    nom = models.CharField(max_length=30, verbose_name="Raison sociale")
    phone = models.CharField(max_length=16, verbose_name="Téléphone", null=True, blank=True)
    adresse1 = models.CharField(max_length=30, verbose_name="Adresse", null=True, blank=True)
    adresse2 = models.CharField(max_length=30, verbose_name="Suite", null=True, blank=True)
    ville = models.CharField(max_length=15, verbose_name="Ville")
    patente = models.CharField(max_length=15, verbose_name="Patente", null=True, blank=True)
    rc = models.CharField(max_length=15, verbose_name="Registre de commerce", null=True, blank=True)
    cnss = models.CharField(max_length=15, verbose_name="Num CNSS", null=True, blank=True)
    idf = models.CharField(max_length=15, verbose_name="Identifiant fiscal", null=True, blank=True)
    actif = models.BooleanField(default=True, verbose_name="Actif")
    ice = models.CharField(max_length=15, verbose_name="ICE", null=True, blank=True)
    logo = models.ImageField(upload_to='logo', blank=True, null=True, verbose_name="Logo")
    forme = models.CharField(max_length=10, verbose_name="Forme juridique", choices=FORMES, null=True, blank=True)

    def __str__(self):
        if self.forme:
            return "{0} {1}".format(self.nom, self.get_forme_display())
        else:
            return self.nom




class Regions(models.TextChoices):
    MA01 = "MA01", "Tanger-Tétouan-Al Hoceïma"
    MA02 = "MA02", "L'Oriental"
    MA03 = "MA03", "Fès-Meknès"
    MA04 = "MA04", "Rabat-Salé-Kénitra"
    MA05 = "MA05", "Béni Mellal-Khénifra"
    MA06 = "MA06", "Casablanca-Settat"
    MA07 = "MA07", "Marrakech-Safi"
    MA08 = "MA08", "Drâa-Tafilalet"
    MA09 = "MA09", "Souss-Massa"
    MA10 = "MA10", "Guelmim-Oued Noun"
    MA11 = "MA11", "Laâyoune-Sakia El Hamra"
    MA12 = "MA12", "Dakhla-Oued Ed-Dahab"
    ATRE = "ATRE", "Autre / Etranger"


class Site(models.Model):
    class Meta:
        ordering = ["nom"]
        verbose_name_plural = "Sites"
        permissions = (
            ('can_access_hht_parameters', 'Gestion des HHT'),
            ('is_admin_for_hht', 'Mode administrateur pour'),
        )
        default_permissions = ['add', 'change', 'view']
        db_table = "base_site"

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    verbose_name = "Site"
    nom = models.CharField(max_length=40, verbose_name="Nom")
    phone = models.CharField(max_length=16, verbose_name="Téléphone", null=True, blank=True)
    adresse1 = models.CharField(max_length=30, verbose_name="Adresse", null=True, blank=True)
    adresse2 = models.CharField(max_length=30, verbose_name="Suite", null=True, blank=True)
    ville = models.CharField(max_length=15, verbose_name="Ville", null=True, blank=True)
    patente = models.CharField(max_length=15, verbose_name="Patente", null=True, blank=True)
    ref = models.CharField(max_length=5, verbose_name="Ref")
    actif = models.BooleanField(default=True, null=True, verbose_name="Actif")


    societe_obj = models.ForeignKey(Societe, verbose_name="Société", related_name="sites", on_delete=models.PROTECT,
                                    limit_choices_to={'actif': True})
    region = models.CharField(max_length=6, verbose_name="Région", choices=Regions.choices)



    def __str__(self):
        return self.nom




    def invoice_footer(self, *args, **kwargs):
        first_line = self.societe_obj.nom
        if self.societe_obj.phone:
            first_line += " - Tél: " + self.societe_obj.phone
        elif self.phone:
            first_line += " - Tél: " + self.phone

        if self.societe_obj.ice:
            first_line += " - ICE: " + self.societe_obj.ice
        second_line = ""
        if self.societe_obj.idf:
            second_line += "Identifiant Fiscal: " + self.societe_obj.idf
        if self.patente:
            if second_line != "":
                second_line += " - "
            second_line += "Patente: " + self.societe_obj.patente
        if self.societe_obj.rc:
            if second_line != "":
                second_line += " - "
            second_line += "RC: " + self.societe_obj.rc
        if self.societe_obj.cnss:
            if second_line != "":
                second_line += " - "
            second_line += "CNSS: " + self.societe_obj.cnss

        if second_line == "":
            return ("", first_line)
        return (first_line, second_line)





class Profile(models.Model):
    ROLE_CHOICES = [
        ('manager', 'Manager'),
        ('superadmin', 'Superadmin'),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.CharField(max_length=20, choices=ROLE_CHOICES)
    sites = models.ManyToManyField(Site, blank=True, verbose_name="Sites")


    def __str__(self):
        return f"{self.user.username} - {self.get_role_display()}"

    def get_user_site(request):
        profile = request.user.profile
        if profile.is_superadmin():
            # Accéder à tous les sites
            sites = Site.objects.all()
        else:
            # Accéder uniquement au site associé au profil
            sites = Site.objects.filter(pk=profile.site.pk)
        return sites


    def is_superadmin(self):
        return self.role == 'superadmin'

base/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import  login_required
from django.contrib.auth import logout as auth_logout
from django.http import HttpResponseRedirect, HttpResponse


@login_required(login_url='/login/')
def Dashboard(request):

    return render(request, 'dashboard.html')

# Create your views here.
@login_required(login_url='/login/')
def logout(request):
    auth_logout(request)
    return HttpResponseRedirect('/login/')


def pdf_response(draw_funk, file_name, *args, **kwargs):
    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = "filename=\"%s\"" % file_name
    draw_funk(response, *args, **kwargs)
    return response

base/templates/layout/header/_menu.html
{% load static %}

	<div id="kt_app_header" class="app-header" data-kt-sticky="true" data-kt-sticky-activate="{default: true, lg: true}" data-kt-sticky-name="app-header-minimize" data-kt-sticky-offset="{default: '200px', lg: '0'}" data-kt-sticky-animation="false">
					<!--begin::Header container-->
					<div class="app-container container-fluid d-flex align-items-stretch justify-content-between" id="kt_app_header_container" style="background-color: #f7f7f7; height: 65px;">
						<!--begin::Sidebar mobile toggle-->
						<div class="d-flex align-items-center d-lg-none ms-n3 me-1 me-md-2" title="Show sidebar menu">
							<div class="btn btn-icon btn-active-color-primary w-35px h-35px" id="kt_app_sidebar_mobile_toggle">
								<i class="ki-duotone ki-abstract-14 fs-2 fs-md-1">
									<span class="path1"></span>
									<span class="path2"></span>
								</i>
							</div>
						</div>
						<!--end::Sidebar mobile toggle-->
						<!--begin::Mobile logo-->
						<div class="d-flex align-items-center flex-grow-1 flex-lg-grow-0">
    {% if request.user.is_superuser %}
        <a href="" class="d-lg-none">
            <img alt="Logo" src="" class="h-30px" />
        </a>
    {% else %}
        <a href="" class="d-lg-none">
            <img alt="Logo" src="" class="h-30px" />
        </a>
    {% endif %}
</div>

						<!--end::Mobile logo-->
						<!--begin::Header wrapper-->
						<div class="d-flex align-items-stretch justify-content-between flex-lg-grow-1" id="kt_app_header_wrapper">
							<!--begin::Menu wrapper-->
							<div class="app-header-menu app-header-mobile-drawer align-items-stretch" data-kt-drawer="true" data-kt-drawer-name="app-header-menu" data-kt-drawer-activate="{default: true, lg: false}" data-kt-drawer-overlay="true" data-kt-drawer-width="250px" data-kt-drawer-direction="end" data-kt-drawer-toggle="#kt_app_header_menu_toggle" data-kt-swapper="true" data-kt-swapper-mode="{default: 'append', lg: 'prepend'}" data-kt-swapper-parent="{default: '#kt_app_body', lg: '#kt_app_header_wrapper'}">
								<!--begin::Menu-->
								<div class="menu menu-rounded menu-column menu-lg-row my-5 my-lg-0 align-items-stretch fw-semibold px-2 px-lg-0" id="kt_app_header_menu" data-kt-menu="true">
									<!--begin:Menu item-->

									<div data-kt-menu-trigger="{default: 'click', lg: 'hover'}" data-kt-menu-placement="bottom-start" class="menu-item here show menu-here-bg menu-lg-down-accordion me-0 me-lg-2">
<span class="menu-link">
    {% if user_sites %}
        <span class="menu-title">
            {% if user_sites|length == 1 %}
                <!-- Si l'utilisateur a un seul site, on l'affiche -->
                {{ user_sites.0.nom }}
            {% else %}
                <!-- Si l'utilisateur a plusieurs sites, on affiche 'Administration' -->
                Administration
            {% endif %}
        </span>
    {% else %}
        <!-- Si l'utilisateur n'a pas de site, on affiche 'Administration' -->
        <span class="menu-title">Administration</span>
    {% endif %}
    <span class="menu-arrow d-lg-none"></span>
</span>


										<!--end:Menu link-->
										<!--begin:Menu sub-->
										<div class="menu-sub menu-sub-lg-down-accordion menu-sub-lg-dropdown p-0 w-100 w-lg-850px">
											<!--begin:Dashboards menu-->
											<div class="menu-state-bg menu-extended overflow-hidden overflow-lg-visible" data-kt-menu-dismiss="true">
												<!--begin:Row-->

											</div>
											<!--end:Dashboards menu-->
										</div>
										<!--end:Menu sub-->
									</div>


								</div>
								<!--end::Menu-->
							</div>

							<!--end::Menu wrapper-->
							<!--begin::Navbar-->
							<div class="app-navbar flex-shrink-0">
								<!--begin::Search-->
								<div class="app-navbar-item align-items-stretch ms-1 ms-md-4">
									<!--begin::Search-->
									<div id="kt_header_search" class="header-search d-flex align-items-stretch" data-kt-search-keypress="true" data-kt-search-min-length="2" data-kt-search-enter="enter" data-kt-search-layout="menu" data-kt-menu-trigger="auto" data-kt-menu-overflow="false" data-kt-menu-permanent="true" data-kt-menu-placement="bottom-end">
										<!--begin::Search toggle-->

										<!--end::Search toggle-->
										<!--begin::Menu-->
										<div data-kt-search-element="content" class="menu menu-sub menu-sub-dropdown p-7 w-325px w-md-375px">
											<!--begin::Wrapper-->
											<div data-kt-search-element="wrapper">
												<!--begin::Form-->
												<form data-kt-search-element="form" class="w-100 position-relative mb-3" autocomplete="off">
													<!--begin::Icon-->
													<i class="ki-duotone ki-magnifier fs-2 text-gray-500 position-absolute top-50 translate-middle-y ms-0">
														<span class="path1"></span>
														<span class="path2"></span>
													</i>
													<!--end::Icon-->
													<!--begin::Input-->
													<input type="text" class="search-input form-control form-control-flush ps-10" name="search" value="" placeholder="Search..." data-kt-search-element="input" />
													<!--end::Input-->
													<!--begin::Spinner-->
													<span class="search-spinner position-absolute top-50 end-0 translate-middle-y lh-0 d-none me-1" data-kt-search-element="spinner">
														<span class="spinner-border h-15px w-15px align-middle text-gray-500"></span>
													</span>
													<!--end::Spinner-->
													<!--begin::Reset-->
													<span class="search-reset btn btn-flush btn-active-color-primary position-absolute top-50 end-0 translate-middle-y lh-0 d-none" data-kt-search-element="clear">
														<i class="ki-duotone ki-cross fs-2 fs-lg-1 me-0">
															<span class="path1"></span>
															<span class="path2"></span>
														</i>
													</span>
													<!--end::Reset-->
													<!--begin::Toolbar-->
													<div class="position-absolute top-50 end-0 translate-middle-y" data-kt-search-element="toolbar">
														<!--begin::Preferences toggle-->
														<div data-kt-search-element="preferences-show" class="btn btn-icon w-20px btn-sm btn-active-color-primary me-1" data-bs-toggle="tooltip" title="Show search preferences">
															<i class="ki-duotone ki-setting-2 fs-2">
																<span class="path1"></span>
																<span class="path2"></span>
															</i>
														</div>
														<!--end::Preferences toggle-->
														<!--begin::Advanced search toggle-->
														<div data-kt-search-element="advanced-options-form-show" class="btn btn-icon w-20px btn-sm btn-active-color-primary" data-bs-toggle="tooltip" title="Show more search options">
															<i class="ki-duotone ki-down fs-2"></i>
														</div>
														<!--end::Advanced search toggle-->
													</div>
													<!--end::Toolbar-->
												</form>
												<!--end::Form-->
												<!--begin::Separator-->
												<div class="separator border-gray-200 mb-6"></div>
												<!--end::Separator-->



											</div>

										</div>
										<!--end::Menu-->
									</div>
									<!--end::Search-->
								</div>
								<!--end::Search-->

								<!--begin::Notifications-->
								<div class="app-navbar-item ms-1 ms-md-4">
									<!--begin::Menu- wrapper-->

									<div class="menu menu-sub menu-sub-dropdown menu-column w-350px w-lg-375px" data-kt-menu="true" id="kt_menu_notifications">
										
										<div class="tab-content">
											<!--begin::Tab panel-->
											<div class="tab-pane fade" id="kt_topbar_notifications_1" role="tabpanel">
												
												<div class="py-3 text-center border-top">
													<a href="pages/user-profile/activity.html" class="btn btn-color-gray-600 btn-active-color-primary">View All
													<i class="ki-duotone ki-arrow-right fs-5">
														<span class="path1"></span>
														<span class="path2"></span>
													</i></a>
												</div>
												<!--end::View more-->
											</div>

										</div>
										<!--end::Tab content-->
									</div>
									<!--end::Menu-->
									<!--end::Menu wrapper-->
								</div>
								<!--end::Notifications-->

	<!----------------------------------------------------------------------->






									<!------------------------------------------------------------------------------------------->

								<!-- User Menu Section -->
<!-- User Menu Section -->
<div class="app-navbar-item ms-1 ms-md-4" id="kt_header_user_menu_toggle" aria-haspopup="true" aria-expanded="false">
<div class="cursor-pointer d-flex align-items-center p-1" data-kt-menu-trigger="{default: 'click', lg: 'hover'}"
     data-kt-menu-attach="parent" data-kt-menu-placement="bottom-end"
     style="border: 2px solid #ddd; border-radius: 10px; width: 120px; background-color: #f9f9f9; box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1); transition: all 0.3s;">
    <img src="{% static 'assets/media/avatars/blank.png' %}" class="rounded-circle border border-light" alt="User Avatar" style="width: 35px; height: 35px; box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);" />
    <span class="ms-3 fs-6 fw-bold text-dark">{{ user.get_full_name }}</span>
</div>








    <!-- User Menu Dropdown -->
    <div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-800 menu-state-bg menu-state-color fw-semibold py-4 fs-6 w-275px" data-kt-menu="true" aria-label="User Menu">

        <!-- User Info Section -->
        <div class="menu-item px-3">
            <div class="menu-content d-flex align-items-center px-3">
                <div class="symbol symbol-50px me-4">
                    <img alt="User Avatar" src="{% static 'assets/media/avatars/blank.png' %}" class="rounded-circle" />
                </div>
                <div class="d-flex flex-column">
                    <div class="fw-bold text-dark fs-5">{{ user.get_full_name }}</div>
                    <a href="mailto:{{ user.email }}" class="text-muted text-hover-primary fs-7">{{ user.email }}</a>
                </div>
            </div>
        </div>
        <div class="separator my-2"></div>

        <!-- Admin Access (Visible only for superusers) -->
        {% if user.is_superuser %}
        <div class="menu-item px-5">
            <a href="/admin/" class="menu-link px-5 text-warning">Admin Dashboard</a>
        </div>
        {% endif %}

        <!-- Menu Items -->
        <div class="separator my-2"></div>
        <div class="menu-item px-5">
            <a href="#" class="menu-link px-5">Security & Login</a>
        </div>
        <div class="menu-item px-5">
            <a href="#" class="menu-link px-5">My Account</a>
        </div>

        <div class="separator my-2"></div>

        <!-- Logout Section -->
        <div class="menu-item px-5">
            <a href="{% url 'base:logout' %}" class="menu-link px-5" aria-label="Logout">Log Out</a>
        </div>
    </div>
</div>

<!-- Mobile Menu Toggle Button -->
<div class="app-navbar-item d-lg-none ms-2 me-n2" title="Show Header Menu">
    <div class="btn btn-flex btn-icon btn-active-color-primary w-30px h-30px" id="kt_app_header_menu_toggle" aria-controls="header-menu" aria-expanded="false">
        <i class="ki-duotone ki-element-4 fs-1">
            <span class="path1"></span>
            <span class="path2"></span>
        </i>
    </div>
</div>

								<!--end::Header menu toggle-->
								<!--begin::Aside toggle-->
								
								<!--end::Header menu toggle-->



							</div>
							<!--end::Navbar-->
						</div>
						<!--end::Header wrapper-->
					</div>
					<!--end::Header container-->
				</div>