base/urls.py
from django.urls import path, re_path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [

    # ---------------------- create -------------------#
    path('', views.Dashboard, name='Dashboard'),
    re_path(r'login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', views.logout, name='logout'),
    # ---------------------- liste -------------------#
    # ---------------------- detail -------------------#

    # ---------------------- autre -------------------#

]

commande/urls.py
from django.urls import path
from . import views

urlpatterns = [

    # ---------------------- create -------------------#
path('create_facture/', views.CreateFactureView.as_view(), name='create_facture'),
    # ---------------------- liste -------------------#
    path('liste/bon_livresion', views.ListeBonLivraisonClinet.as_view(), name='bon_livresion'),
    path('direct/facture', views.ListFactureView.as_view(), name='factur'),

    # ---------------------- detail -------------------#
    path('bon_livresion/detail/<int:pk>/', views.DetailBonLivresionCLient.as_view(), name='bon_livresion_detail'),
    # ---------------------- autre -------------------#
    path('invoicebonlivraison/<int:pk>/print/', views.invoice_bonlivraison, name='printInvoivebonlivraison'),
    path('invoice/<int:pk>/print/', views.invoice_pdf_view, name='printInvoive'),
    # ---------------------- update -------------------#


]

gestion_commercial/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = ([
    path('admin/', admin.site.urls),
    re_path(r'^', include(('base.urls', 'base'), namespace="base")),
    re_path(r'^', include(('stock.urls', 'stock'), namespace="stock")),
    re_path(r'^', include(('client.urls', 'client'), namespace="client")),
    re_path(r'^', include(('dashboard.urls', 'dashboard'), namespace="dashboard")),
    re_path(r'^', include(('produit.urls', 'produit'), namespace="produit")),
    re_path(r'^', include(('venteAchats.urls', 'venteAchats'), namespace="venteAchats")),
    re_path(r'^', include(('commande.urls', 'commande'), namespace="commandes")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
if settings.DEBUG:  # Assurez-vous que les URL de debug toolbar ne sont chargées qu'en mode développement
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

commande/forms.py
from commande.models import BonLivraisonClinet
from crispy_forms.helper import FormHelper




class BonLivraisonClinetFormHelper(FormHelper):
    model = BonLivraisonClinet
    form_tag = False
    form_class = 'd-flex flex-column flex-md-row gap-5'
    field_class = 'flex-row-fluid mae-filter-form'
    help_text_inline = True
    form_show_labels = False

commande/templates/bon_livresion/bon_livresion.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}
Liste des Commandes
{% endblock %}

{% block css %}
<link href="{% static 'assets/css/table.css' %}" rel="stylesheet" type="text/css"/>
{% endblock css %}

{% block toolbar %}
<div id="kt_app_toolbar" class="app-toolbar mt-1" style="height: 50px;">
    <!--begin::Toolbar container-->
    <div id="kt_app_toolbar_container" class="app-container container-fluid d-flex flex-stack">
        <!--begin::Page title-->
        <div class="page-title d-flex flex-column justify-content-center flex-wrap me-3">
            <!--begin::Title-->
            <h1 class="page-heading d-flex text-gray-900 fw-bold fs-3 flex-column justify-content-center my-0">Liste Bon livresion</h1>
            <!--end::Title-->
            <!--begin::Breadcrumb-->
            <ul class="breadcrumb breadcrumb-separatorless fw-semibold fs-7 my-0 pt-1">
                <!--begin::Item-->
                <li class="breadcrumb-item text-muted">
                    <a href="" class="text-muted text-hover-primary">Accueil</a>
                </li>
                <!--end::Item-->
                <!--begin::Item-->
                <li class="breadcrumb-item">
                    <span class="bullet bg-gray-500 w-5px h-2px"></span>
                </li>
                <!--end::Item-->
                <!--begin::Item-->
                <li class="breadcrumb-item text-muted">Liste Bon livresiont</li>
                <!--end::Item-->
            </ul>
            <!--end::Breadcrumb-->
        </div>
        <!--end::Page title-->
    </div>

    <!-- Align elements with the height of the toolbar -->
    <div class="d-flex align-items-center gap-2 me-4" style="height: 100%;">
        <!--begin::Action wrapper-->
        <div class="d-flex align-items-center">
            <span class="fs-7 fw-bold text-gray-700 pe-4 text-nowrap d-none d-md-block">Commandes:</span>
            <span class="badge badge-light-primary fs-base" id="id_nb_orders">0</span>
        </div>

        <!--end::Action wrapper-->
        <div class="bullet bg-secondary h-100 w-1px mx-6"></div>
        <!--begin::Action wrapper-->
        <div class="d-flex align-items-center">
            <span class="fs-7 fw-bold text-gray-700 pe-4 text-nowrap d-none d-md-block">Montant:</span>
            <span class="badge badge-light-primary fs-base" id="id_montant">0,00</span>
        </div>
        <!--end::Action wrapper-->
        <div class="bullet bg-secondary h-100 w-1px mx-6"></div>

        <div class="d-flex align-items-center">
            <!-- Conteneur pour les messages d'erreur -->
            <div id="error-message" class="alert alert-danger d-none mt-4" role="alert">
                Attention : Les bons de livraison appartiennent à des clients différents. Veuillez sélectionner des bons appartenant au même client.
            </div>

            <form action="{% url 'commande:create_facture' %}" method="post" autocomplete="off" id="acceptForm">
                {% csrf_token %}
                <input type="hidden" name="selected_bons" id="selected_bons" value="">
                <button class="btn btn-block btn-sm btn-primary d-flex align-items-center mt-4 mb-4 " id="accepterBtn" type="button" data-bs-toggle="modal" data-bs-target="#attentionModal" disabled style="width: 120px;">
                    <span class="menu-icon">
                        <i class="bi bi-check-circle fs-2"></i>
                    </span>
                    Gérer Facture
                </button>
            </form>

            <!-- Modal d'attention -->
            <div class="modal fade" id="attentionModal" tabindex="-1" aria-labelledby="attentionModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="attentionModalLabel">Attention</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            Attention : Les bons de livraison appartiennent à des clients différents. Veuillez sélectionner des bons appartenant au même client.
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
                            <button type="button" class="btn btn-primary" id="confirmAction">Confirmer</button>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>




{% endblock %}

{% block content %}
<!-- Modal HTML -->
<div class="modal fade" id="errorModal" tabindex="-1" aria-labelledby="errorModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="errorModalLabel">Erreur</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="errorModalMessage">
                <!-- Message d'erreur sera injecté ici -->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
            </div>
        </div>
    </div>
</div>



<div class="mt-6">
    {% include 'base/includes/list_filter.html' %}
</div>

{% include 'base/includes/list_table.html' %}
{% endblock content %}

{% block javascript %}

<script src="{% static 'assets/js/jquery.min.js' %}"></script>

<script>
$(document).ready(function() {
    function updateTotals() {
        let selectedRows = $('.checkbox_local:checked');
        let nombreSelectionnes = selectedRows.length;
        let montantTotal = 0.0;

        let selectedBons = [];
        let clients = new Set();

        selectedRows.each(function() {
            let montantHtCell = $(this).closest('tr').find('td[data-field="montant"]');
            let montantHtAmount = parseFloat(montantHtCell.text().replace(/[^0-9.,]+/g, "")) || 0;
            montantTotal += montantHtAmount;

            selectedBons.push($(this).val());

            let clientCell = $(this).closest('tr').find('td[data-field="client"]');
            let client = clientCell.text().trim();
            clients.add(client);
        });

        $('#id_nb_orders').text(nombreSelectionnes);
        $('#id_montant').text(montantTotal.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, " ").replace('.', ','));
        $('#selected_bons').val(selectedBons.join(','));

        if (clients.size > 1) {
            $('#errorModalMessage').text("Attention : Les bons de livraison appartiennent à des clients différents. Veuillez sélectionner des bons appartenant au même client.");
            $('#errorModal').modal('show');
            $("#accepterBtn").prop("disabled", true);
        } else {
            $('#errorModal').modal('hide');
            $("#accepterBtn").prop("disabled", nombreSelectionnes === 0);
        }
    }

    $(document).on('change', '.checkbox_local', updateTotals);
    $(document).on('change', '#toggleCB', function() {
        $('.checkbox_local').prop("checked", this.checked);
        updateTotals();
    });
});
</script>


<script>
    document.addEventListener('DOMContentLoaded', function() {
    const confirmButton = document.getElementById('confirmAction');
    const acceptButton = document.getElementById('accepterBtn');

    confirmButton.addEventListener('click', function() {
        // Logique pour traiter la demande de gestion de facture
        console.log('Facture gérée');

        // Ici, tu pourrais soumettre le formulaire ou rediriger l'utilisateur
        document.getElementById('acceptForm').submit();
    });
});

</script>
{% endblock %}

commande/templates/bon_livresion/detail_bon_livresion_client.html
{% extends "base/base.html" %}
{% load static %}
{% load django_tables2 %}

{% block title %}Détails Vente{% endblock %}

{% block css %}
<style>
    /* Custom CSS for enhancing the sales details layout */
    .card-title h3, h4, h3.text-gray-600 {
        font-weight: bold;
        color: #4a5568;
    }

    .table-responsive table {
        border-collapse: collapse;
    }

    .table-bordered th, .table-bordered td {
        padding: 12px;
        border: 1px solid #dee2e6;
    }

    .table-primary th {
        background-color: #e9ecef;
    }

    .table-secondary td {
        background-color: #f8f9fa;
    }

    /* Highlight important details */
    .fw-bolder {
        font-weight: 600;
    }
</style>
{% endblock css %}

{% block toolbar %}
<div id="kt_app_toolbar" class="app-toolbar mt-1" style="height: 50px">
    <div id="kt_app_toolbar_container" class="app-container container-fluid d-flex flex-stack align-items-center">
        <!-- Page Title and Breadcrumb -->
        <div class="d-flex flex-column justify-content-center flex-wrap me-3">
            <h1 class="page-heading text-gray-900 fw-bold fs-3">Détails Vente</h1>
            <ul class="breadcrumb breadcrumb-separatorless fw-semibold fs-7 my-0 pt-1">
                <li class="breadcrumb-item text-muted">
                    <a href="" class="text-muted text-hover-primary">Accueil</a>
                </li>
                <li class="breadcrumb-item">
                    <span class="bullet bg-gray-500 w-5px h-2px"></span>
                </li>
                <li class="breadcrumb-item text-muted">Détails Vente</li>
            </ul>
        </div>

        <!-- Imprimer Button -->
         <div class="d-flex align-items-center">

            <a href="{% url 'commande:printInvoivebonlivraison' pk=vente.pk %}" class="btn btn-sm btn-primary">Imprimer Bon de livraison</a>
        </div>
    </div>
</div>

{% endblock toolbar %}

{% block content %}
<div class="d-flex flex-column flex-column-fluid mt-4 mb-4">
    <div id="kt_app_content_container">
        <div class="d-flex flex-column flex-row-fluid gap-6 gap-lg-6">
            <div class="card-body card-flush pt-0 py-4">
                <div class="card card-flush pt-3 mb-2 mb-xl-10">
                    <div class="card-header">
                        <div class="card-title">
                            <h3 class="text-gray-600">Détails Vente Client : {{ vente.client.nom }}</h3>
                        </div>

                    </div>
                    <div class="separator separator-dashed border-primary my-2 mb-3"></div>

                    <div class="card-body pt-2">
                        <!-- Print Bon de Livraison Button -->

                        <!-- Client Information -->
                        <h4 class="text-gray-600">Informations du Client</h4>
                        <div class="row align-items-start mb-3">
                            <div class="col-lg-4 mb-3">
                                <div class="row">
                                    <div class="col-5 fs-6 text-end">Client:</div>
                                    <div class="col-7 fw-bolder">{{ vente.client.nom }}</div>
                                </div>
                            </div>
                            <div class="col-lg-4 mb-3">
                                <div class="row">
                                    <div class="col-5 fs-6 text-end">Référence:</div>
                                    <div class="col-7 fw-bolder">{{ vente.client.external_id }}</div>
                                </div>
                            </div>
                            <div class="col-lg-4 mb-3">
                                <div class="row">
                                    <div class="col-5 fs-6 text-end">Date:</div>
                                    <div class="col-7 fw-bolder">{{ vente.date_vente|date:"d/m/Y" }}</div>
                                </div>
                            </div>
                        </div>
                        <div class="separator separator-dashed border-primary my-2 mb-3"></div>

                        <!-- Sales Information -->
                        <h4 class="text-gray-600">Informations de la Vente</h4>
                        <div class="row align-items-start mb-3">
                            <div class="col-lg-4 mb-3">
                                <div class="row">
                                    <div class="col-5 fs-6 text-end">Montant Total:</div>
                                    <div class="col-7 fw-bolder">{{ vente.total|floatformat:2 }}</div>
                                </div>
                            </div>
                            <div class="col-lg-4 mb-3">
                                <div class="row">
                                    <div class="col-5 fs-6 text-end">Méthode de Paiement:</div>
                                    <div class="col-7 fw-bolder">{{ vente.methode_de_paiement }}</div>
                                </div>
                            </div>
                        </div>
                        <div class="separator separator-dashed border-primary my-2 mb-3"></div>

                        <!-- Sales Items Table -->
                        <h3 class="text-gray-600">Les Articles de la Vente</h3>
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover">
                                <thead class="table-primary">
                                    <tr>
                                        <th>Article</th>
                                        <th>Quantité</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for article in articles %}
                                    <tr>
                                        <td>{{ article.article.nom }}</td>
                                        <td>{{ article.quantite }}</td>
                                    </tr>
                                    {% empty %}
                                    <tr>
                                        <td colspan="3" class="text-center">Aucun article trouvé.</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                                <tfoot class="table-secondary">
                                    <tr>
                                        <td><strong>Total</strong></td>
                                        <td><strong>{{ total_quantity }}</strong></td>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block javascript %}
<script>
    function printBonLivraison() {
        // This URL should point to the view generating the printable "Bon de Livraison" PDF
        const printUrl = "";

        // Open the URL in a new tab for printing
        window.open(printUrl, '_blank');
    }
</script>
{% endblock javascript %}