base/urls.py
from django.urls import path, re_path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [

    # ---------------------- create -------------------#
    path('', views.Dashboard, name='Dashboard'),
    re_path(r'login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', views.logout, name='logout'),
    # ---------------------- liste -------------------#
    # ---------------------- detail -------------------#

    # ---------------------- autre -------------------#

]

client/urls.py
from django.urls import path
from . import views

urlpatterns = [

    # ---------------------- create -------------------#

    # ---------------------- liste -------------------#
    path('client/list', views.ListClient.as_view(), name='list_client'),

    # ---------------------- detail -------------------#

    # ---------------------- autre -------------------#

]

commande/urls.py
from django.urls import path
from . import views

urlpatterns = [

    # ---------------------- create -------------------#
path('create_facture/', views.CreateFactureView.as_view(), name='create_facture'),
    # ---------------------- liste -------------------#
    path('liste/bon_livresion', views.ListeBonLivraisonClinet.as_view(), name='bon_livresion'),
    path('direct/facture', views.ListFactureView.as_view(), name='factur'),

    # ---------------------- detail -------------------#
    path('bon_livresion/detail/<int:pk>/', views.DetailBonLivresionCLient.as_view(), name='bon_livresion_detail'),
    # ---------------------- autre -------------------#
    path('invoicebonlivraison/<int:pk>/print/', views.invoice_bonlivraison, name='printInvoivebonlivraison'),
    path('invoice/<int:pk>/print/', views.invoice_pdf_view, name='printInvoive'),
    # ---------------------- update -------------------#


]

gestion_commercial/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = ([
    path('admin/', admin.site.urls),
    re_path(r'^', include(('base.urls', 'base'), namespace="base")),
    re_path(r'^', include(('stock.urls', 'stock'), namespace="stock")),
    re_path(r'^', include(('client.urls', 'client'), namespace="client")),
    re_path(r'^', include(('dashboard.urls', 'dashboard'), namespace="dashboard")),
    re_path(r'^', include(('produit.urls', 'produit'), namespace="produit")),
    re_path(r'^', include(('venteAchats.urls', 'venteAchats'), namespace="venteAchats")),
    re_path(r'^', include(('commande.urls', 'commande'), namespace="commandes")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
if settings.DEBUG:  # Assurez-vous que les URL de debug toolbar ne sont chargées qu'en mode développement
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

venteAchats/urls.py
from django.urls import path
from . import views
from .views import get_prices
urlpatterns = [

    # ---------------------- create -------------------#
    path('vente/create', views.vente_create, name='Size_vente'),
    # ---------------------- liste -------------------#
    path('liste/vente/client', views.ListeVenteClient.as_view(), name='List_vente_client'),

    # ---------------------- detail -------------------#
    path('Vente_client/detail/<int:pk>/', views.DetailVenteCLient.as_view(), name='vente_client_detail'),
    # ---------------------- autre -------------------#
    path('get-prices/<int:client_id>/', get_prices, name='get_prices'),


]

base/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.exceptions import ValidationError


from django.utils.functional import lazy


class AbstractBaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted = models.BooleanField(default=False)


    class Meta:
        abstract = True
        default_permissions = ['add', 'change', 'view', "soft_delete"]

    def soft_delete(self):
        # Get the classes that reference self that are instances of BaseModel and are not soft deleted
        for f in self._meta.get_fields():
            if f.one_to_many or f.one_to_one:
                if issubclass(f.related_model, AbstractBaseModel) and \
                        f.related_model.objects.filter(**{f.field.name: self}, deleted=False).exists():
                    raise ValidationError(
                        "Vous ne pouvez pas supprimer cet élément car il est référencé par au moins un élément de type {0}".format(
                            f.related_model._meta.verbose_name))
        self.deleted = True
        self.save()




class Societe(models.Model):
    FORMES = (
        ('sarl', 'SARL'),
        ('sarlau', 'SARL AU'),
        ('sa', 'SA'),
    )

    class Meta:
        ordering = ["nom"]
        verbose_name_plural = "Sociétés"
        default_permissions = ['add', 'change', 'view']
        db_table = "base_company"

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    verbose_name = "Société"
    nom = models.CharField(max_length=30, verbose_name="Raison sociale")
    phone = models.CharField(max_length=16, verbose_name="Téléphone", null=True, blank=True)
    adresse1 = models.CharField(max_length=30, verbose_name="Adresse", null=True, blank=True)
    adresse2 = models.CharField(max_length=30, verbose_name="Suite", null=True, blank=True)
    ville = models.CharField(max_length=15, verbose_name="Ville")
    patente = models.CharField(max_length=15, verbose_name="Patente", null=True, blank=True)
    rc = models.CharField(max_length=15, verbose_name="Registre de commerce", null=True, blank=True)
    cnss = models.CharField(max_length=15, verbose_name="Num CNSS", null=True, blank=True)
    idf = models.CharField(max_length=15, verbose_name="Identifiant fiscal", null=True, blank=True)
    actif = models.BooleanField(default=True, verbose_name="Actif")
    ice = models.CharField(max_length=15, verbose_name="ICE", null=True, blank=True)
    logo = models.ImageField(upload_to='logo', blank=True, null=True, verbose_name="Logo")
    forme = models.CharField(max_length=10, verbose_name="Forme juridique", choices=FORMES, null=True, blank=True)

    def __str__(self):
        if self.forme:
            return "{0} {1}".format(self.nom, self.get_forme_display())
        else:
            return self.nom




class Regions(models.TextChoices):
    MA01 = "MA01", "Tanger-Tétouan-Al Hoceïma"
    MA02 = "MA02", "L'Oriental"
    MA03 = "MA03", "Fès-Meknès"
    MA04 = "MA04", "Rabat-Salé-Kénitra"
    MA05 = "MA05", "Béni Mellal-Khénifra"
    MA06 = "MA06", "Casablanca-Settat"
    MA07 = "MA07", "Marrakech-Safi"
    MA08 = "MA08", "Drâa-Tafilalet"
    MA09 = "MA09", "Souss-Massa"
    MA10 = "MA10", "Guelmim-Oued Noun"
    MA11 = "MA11", "Laâyoune-Sakia El Hamra"
    MA12 = "MA12", "Dakhla-Oued Ed-Dahab"
    ATRE = "ATRE", "Autre / Etranger"


class Site(models.Model):
    class Meta:
        ordering = ["nom"]
        verbose_name_plural = "Sites"
        permissions = (
            ('can_access_hht_parameters', 'Gestion des HHT'),
            ('is_admin_for_hht', 'Mode administrateur pour'),
        )
        default_permissions = ['add', 'change', 'view']
        db_table = "base_site"

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    verbose_name = "Site"
    nom = models.CharField(max_length=40, verbose_name="Nom")
    phone = models.CharField(max_length=16, verbose_name="Téléphone", null=True, blank=True)
    adresse1 = models.CharField(max_length=30, verbose_name="Adresse", null=True, blank=True)
    adresse2 = models.CharField(max_length=30, verbose_name="Suite", null=True, blank=True)
    ville = models.CharField(max_length=15, verbose_name="Ville", null=True, blank=True)
    patente = models.CharField(max_length=15, verbose_name="Patente", null=True, blank=True)
    ref = models.CharField(max_length=5, verbose_name="Ref")
    actif = models.BooleanField(default=True, null=True, verbose_name="Actif")


    societe_obj = models.ForeignKey(Societe, verbose_name="Société", related_name="sites", on_delete=models.PROTECT,
                                    limit_choices_to={'actif': True})
    region = models.CharField(max_length=6, verbose_name="Région", choices=Regions.choices)



    def __str__(self):
        return self.nom




    def invoice_footer(self, *args, **kwargs):
        first_line = self.societe_obj.nom
        if self.societe_obj.phone:
            first_line += " - Tél: " + self.societe_obj.phone
        elif self.phone:
            first_line += " - Tél: " + self.phone

        if self.societe_obj.ice:
            first_line += " - ICE: " + self.societe_obj.ice
        second_line = ""
        if self.societe_obj.idf:
            second_line += "Identifiant Fiscal: " + self.societe_obj.idf
        if self.patente:
            if second_line != "":
                second_line += " - "
            second_line += "Patente: " + self.societe_obj.patente
        if self.societe_obj.rc:
            if second_line != "":
                second_line += " - "
            second_line += "RC: " + self.societe_obj.rc
        if self.societe_obj.cnss:
            if second_line != "":
                second_line += " - "
            second_line += "CNSS: " + self.societe_obj.cnss

        if second_line == "":
            return ("", first_line)
        return (first_line, second_line)





class Profile(models.Model):
    ROLE_CHOICES = [
        ('manager', 'Manager'),
        ('superadmin', 'Superadmin'),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.CharField(max_length=20, choices=ROLE_CHOICES)
    sites = models.ManyToManyField(Site, blank=True, verbose_name="Sites")


    def __str__(self):
        return f"{self.user.username} - {self.get_role_display()}"

    def get_user_site(request):
        profile = request.user.profile
        if profile.is_superadmin():
            # Accéder à tous les sites
            sites = Site.objects.all()
        else:
            # Accéder uniquement au site associé au profil
            sites = Site.objects.filter(pk=profile.site.pk)
        return sites


    def is_superadmin(self):
        return self.role == 'superadmin'

base/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import  login_required
from django.contrib.auth import logout as auth_logout
from django.http import HttpResponseRedirect, HttpResponse


@login_required(login_url='/login/')
def Dashboard(request):

    return render(request, 'dashboard.html')

# Create your views here.
@login_required(login_url='/login/')
def logout(request):
    auth_logout(request)
    return HttpResponseRedirect('/login/')


def pdf_response(draw_funk, file_name, *args, **kwargs):
    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = "filename=\"%s\"" % file_name
    draw_funk(response, *args, **kwargs)
    return response

base/templates/layout/aside/_menu.html
{% load static %}
<style>
    #kt_app_sidebar_toggle:hover {
    box-shadow: 0px 0px 20px rgba(16, 185, 129, 0.6);
}
#kt_app_sidebar_toggle:hover i {
    color: #34D399;
}

</style>
<div id="kt_app_sidebar" class="app-sidebar flex-column" data-kt-drawer="true"
     data-kt-drawer-name="app-sidebar" data-kt-drawer-activate="{default: true, lg: false}"
     data-kt-drawer-overlay="true" data-kt-drawer-width="250px" data-kt-drawer-direction="start"
     data-kt-drawer-toggle="#kt_app_sidebar_mobile_toggle" style="background-color: #003545;">
    <!--begin::Logo-->
    <div class="app-sidebar-logo px-6 py-3" id="kt_app_sidebar_logo" style="text-align: center;">

        <a href="" class="{% if not request.user.is_superuser %}d-none{% endif %}">
            <img alt="Logo" src=""
                 class="h-65px w-200px app-sidebar-logo-default"/>
            <img alt="Logo" src=""
                 class="h-25px app-sidebar-logo-minimize"/>
        </a>


        <div id="kt_app_sidebar_toggle"
     class="app-sidebar-toggle btn btn-icon btn-sm h-40px w-40px position-absolute top-50 start-100 translate-middle"
     data-kt-toggle="true" data-kt-toggle-state="active" data-kt-toggle-target="body"
     data-kt-toggle-name="app-sidebar-minimize"
     style="border-radius: 10px; background-color: #1F2937; box-shadow: 0 0 10px rgba(255, 255, 255, 0.2); transition: all 0.3s ease;">
    <i class="ki-duotone ki-arrow-left fs-3"
       style="color: #10B981; transition: color 0.3s ease;">
        <span class="path1"></span>
        <span class="path2"></span>
    </i>
</div>



        <!--end::Sidebar toggle-->
    </div>
    <!--end::Logo-->
    <!--begin::sidebar menu-->
    <div class="app-sidebar-menu overflow-hidden flex-column-fluid">
        <!--begin::Menu wrapper-->
        <div id="kt_app_sidebar_menu_wrapper" class="app-sidebar-wrapper">
            <!--begin::Scroll wrapper-->
            <div id="kt_app_sidebar_menu_scroll" class="scroll-y my-5 mx-3" data-kt-scroll="true"
                 data-kt-scroll-activate="true" data-kt-scroll-height="auto"
                 data-kt-scroll-dependencies="#kt_app_sidebar_logo, #kt_app_sidebar_footer"
                 data-kt-scroll-wrappers="#kt_app_sidebar_menu" data-kt-scroll-offset="5px"
                 data-kt-scroll-save-state="true">
                <!--begin::Menu-->
                <div class="menu menu-column menu-rounded menu-sub-indention fw-semibold fs-6"
                     id="#kt_app_sidebar_menu" data-kt-menu="true" data-kt-menu-expand="false">
                    <!--begin:Menu item-->
                    <div data-kt-menu-trigger="click" class="menu-item here show menu-accordion">
                        <!--begin:Menu link-->
                        {% if request.user.is_superuser %}
                        <a href="">

                            {% else %}
                            <a href="">

                                {% endif %}

                                <span class="menu-link">
												<span class="menu-icon">
													<i class="ki-duotone ki-element-11 fs-2">
														<span class="path1"></span>
														<span class="path2"></span>
														<span class="path3"></span>
														<span class="path4"></span>
													</i>
												</span>
												<span class="menu-title">Dashboards</span>

											</span>
                            </a>
                        </a>
                    </div>
                    <div class="menu-item pt-5">
                        <!--begin:Menu content-->
                        <div class="menu-content">
                            <span class="menu-heading fw-bold text-uppercase fs-7">Clients</span>
                        </div>
                        <!--end:Menu content-->
                    </div>
                    <div data-kt-menu-trigger="click"
                         class="menu-item menu-accordion  {% if active_menu == 'clients' %}here show{% endif %} ">
                        <!--begin:Menu link-->
                        <span class="menu-link">
										<span class="menu-icon">
											<i class="bi bi-people fs-2">
											</i>
										</span>
										<span class="menu-title">Gestion Clients</span>
										<span class="menu-arrow"></span>
									</span>
                        <!--end:Menu link-->
                        <!--begin:Menu sub-->
                        <div class="menu-sub menu-sub-accordion">

                            <div class="menu-item">
                                <!--begin:Menu link-->

                                <a class="menu-link {% if active_item == 'client_list'  and active_menu == 'clients'  %}active{% endif %}"
                                    href="{% url 'client:list_client' %}">
												<span class="menu-bullet">
													<span class="bullet bullet-dot"></span>
												</span>
                                    <span class="menu-title">Clients suivis</span>
                                </a>
                                <!--end:Menu link-->
                            </div>

                        </div>
                        <!--end:Menu sub-->
                    </div>
  <div class="menu-item pt-5">
                        <!--begin:Menu content-->
                        <div class="menu-content">
                            <span class="menu-heading fw-bold text-uppercase fs-7">Vente</span>
                        </div>
                        <!--end:Menu content-->
                    </div>
                    <div data-kt-menu-trigger="click"
                         class="menu-item menu-accordion  {% if active_menu == 'ventes' %}here show{% endif %} ">
                        <!--begin:Menu link-->
                        <span class="menu-link">
										<span class="menu-icon">
											<i class="bi bi-people fs-2">
											</i>
										</span>
										<span class="menu-title">Saisie des Vente</span>
										<span class="menu-arrow"></span>
									</span>
                        <!--end:Menu link-->
                        <!--begin:Menu sub-->
                        <div class="menu-sub menu-sub-accordion">

                            <div class="menu-item">
                                <!--begin:Menu link-->

                                <a class="menu-link {% if active_item == 'vente_create'  and active_menu == 'ventes'  %}active{% endif %}"
                                   href="{% url 'venteAchats:Size_vente' %}">
												<span class="menu-bullet">
													<span class="bullet bullet-dot"></span>
												</span>
                                    <span class="menu-title">Vente Vendeur</span>
                                </a>
                                <!--end:Menu link-->
                            </div>
                               <div class="menu-item">
                                <!--begin:Menu link-->

                                <a class="menu-link {% if active_item == 'vente_create'  and active_menu == 'ventes'  %}active{% endif %}"
                                   href="{% url 'venteAchats:Size_vente' %}">
												<span class="menu-bullet">
													<span class="bullet bullet-dot"></span>
												</span>
                                    <span class="menu-title">Vente Client</span>
                                </a>
                                <!--end:Menu link-->
                            </div>

                        </div>
                        <!--end:Menu sub-->
                    </div>
                      <div data-kt-menu-trigger="click"
                         class="menu-item menu-accordion  {% if active_menu == 'ventes' %}here show{% endif %} ">
                        <!--begin:Menu link-->
                        <span class="menu-link">
										<span class="menu-icon">
											<i class="bi bi-people fs-2">
											</i>
										</span>
										<span class="menu-title">Liste des Vente</span>
										<span class="menu-arrow"></span>
									</span>
                        <!--end:Menu link-->
                        <!--begin:Menu sub-->
                        <div class="menu-sub menu-sub-accordion">

                            <div class="menu-item">
                                <!--begin:Menu link-->

                                <a class="menu-link {% if active_item == 'vente_create'  and active_menu == 'ventes'  %}active{% endif %}"
                                   href="{% url 'venteAchats:Size_vente' %}">
												<span class="menu-bullet">
													<span class="bullet bullet-dot"></span>
												</span>
                                    <span class="menu-title">Liste Vente Vendeur</span>
                                </a>
                                <!--end:Menu link-->
                            </div>

                               <div class="menu-item">
                                <!--begin:Menu link-->

                                <a class="menu-link {% if active_item == 'vente_create'  and active_menu == 'ventes'  %}active{% endif %}"
                                       href="{% url 'venteAchats:List_vente_client' %}">
												<span class="menu-bullet">
													<span class="bullet bullet-dot"></span>
												</span>
                                    <span class="menu-title">Liste Vente Client</span>
                                </a>
                                <!--end:Menu link-->
                            </div>
                             <div class="menu-item">
                                <!--begin:Menu link-->

                                <a class="menu-link {% if active_item == 'bon_livresion'  and active_menu == 'bon_livresions'  %}active{% endif %}"
                                       href="{% url 'commande:bon_livresion' %}">
												<span class="menu-bullet">
													<span class="bullet bullet-dot"></span>
												</span>
                                    <span class="menu-title">Liste Bon Livresion</span>
                                </a>
                                <!--end:Menu link-->
                            </div>
                              <div class="menu-item">
                                <!--begin:Menu link-->

                                <a class="menu-link {% if active_item == 'bon_livresion'  and active_menu == 'bon_livresions'  %}active{% endif %}"
                                       href="{% url 'commande:factur' %}">
												<span class="menu-bullet">
													<span class="bullet bullet-dot"></span>
												</span>
                                    <span class="menu-title">facture</span>
                                </a>
                                <!--end:Menu link-->
                            </div>


                        </div>
                        <!--end:Menu sub-->
                    </div>
  <div class="menu-item pt-5">
                        <!--begin:Menu content-->
                        <div class="menu-content">
                            <span class="menu-heading fw-bold text-uppercase fs-7">Achate</span>
                        </div>
                        <!--end:Menu content-->
                    </div>
                    <div data-kt-menu-trigger="click"
                         class="menu-item menu-accordion  {% if active_menu == 'clients' %}here show{% endif %} ">
                        <!--begin:Menu link-->
                        <span class="menu-link">
										<span class="menu-icon">
											<i class="bi bi-people fs-2">
											</i>
										</span>
										<span class="menu-title">Gestion des Achate</span>
										<span class="menu-arrow"></span>
									</span>
                        <!--end:Menu link-->
                        <!--begin:Menu sub-->
                        <div class="menu-sub menu-sub-accordion">

                            <div class="menu-item">
                                <!--begin:Menu link-->

                                <a class="menu-link {% if active_item == 'client_list'  and active_menu == 'clients'  %}active{% endif %}"
                                   href="">
												<span class="menu-bullet">
													<span class="bullet bullet-dot"></span>
												</span>
                                    <span class="menu-title">Saisie Achate</span>
                                </a>
                                <!--end:Menu link-->
                            </div>

                        </div>
                        <!--end:Menu sub-->
                    </div>


                </div>

            </div>

        </div>

    </div>


</div>
<script>
    $(document).ready(function () {
    $('[data-kt-menu-trigger="click"]').on('click', function (e) {
        e.stopPropagation(); // Empêche la propagation de l'événement
        $(this).find('.menu-sub').toggle(); // Affiche ou masque le sous-menu
    });
});

</script>